name: "Docker: Test"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:

  docker:
    name: "Docker: Build,Test"
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      -
        name: Build Docker Test Image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        id: build
        with:
          context: .
          load: true
          tags: |
            test

      -
        name: Run Docker Image
        run: |
          docker run \
            -d \
            -p 3128:3128 \
            -e SQUID_USER=DEFAULT_USER \
            -e SQUID_PASS=DEFAULT_PASSWORD \
            --name=test \
            test

      -
        name: Test Docker Image
        run: |
          python test.py
