name: "Docker: Test"

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:

  docker:
    name: "Docker: Build,Test"
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      -
        name: Build Docker Test Image
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6
        id: build
        with:
          context: .
          load: true
          tags: |
            test

      -
        name: Run Docker Image
        run: |
          docker run \
            -d \
            -p 3128:3128 \
            -e SQUID_USER=DEFAULT_USER \
            -e SQUID_PASS=DEFAULT_PASSWORD \
            --name=test \
            test

      -
        name: Test Docker Image
        run: |
          python test.py
